### ISSUE TITLE
Notifications do not work

### ISSUE THREAD

**Issue by HashEngineering** [hodlwallet/hodl-wallet-android#44]
Notifications do not work if turned ON on Android 8.1 and higher based on my testing.  I am forking this app for another coin and found this to be the case.  Additionally, by adding some code to create notification channels, then this can be resolved.

I can submit a pull request with a solution, if there is interest.

**Comment by igorgue** [comment]
Hi @HashEngineering yes make the pr 👍 thank you!

**Comment by gruve-p** [comment]
This can be closed now because https://github.com/hodlwallet/hodl-wallet-android/pull/45 is merged
