### ISSUE TITLE
[Feature Request] Ability to see wallet's xpub

### ISSUE THREAD

**Issue by benthecarman** [hodlwallet/hodl-wallet-android#49]
It would be nice to see the wallet's xpub so I can import it to my full node's watch only wallet.

**Comment by igorgue** [comment]
Hey, Xpub format would be nice, but the wallet is a BIP32 wallet, in the future, we will be upgrading that so you can have accounts with xpubs to import, right now would be a mess since not many wallets support our derivation path.
