### ISSUE TITLE
Please update your build instructions such that reproducible builds are possible

### ISSUE THREAD

**Issue by Giszmo** [hodlwallet/hodl-wallet-android#50]
As far as I can see, HODL is a clone of BRD and I [tried to reproduce the build](https://walletscrutiny.com/posts/co.hodlwallet/) but failed and had to guess a few times along the way.

Please reply here once you have these issues fixed.

**Comment by ndalliard** [comment]
Why was this closed? Does it mean HODL Wallet is not reproducible?

**Comment by igorgue** [comment]
@ndalliard No, you can always build HODL Wallet, it means I won't pander to some dude that wants to trash every single wallet in the space :)

**Comment by ndalliard** [comment]
I am just asking for my site. Nothing wrong about not having reproducible builds.

Building the wallet is one thing, but that doesn't mean it's reproducible.

**Comment by igorgue** [comment]
@ndalliard No we don't have reproducible builds, and that has never stopped anyone from contributing, and there has never been interest for having reproducible builds, I don't do CI on this so...

I understand for some this might be very important, pull requests are welcome!

**Comment by Giszmo** [comment]
If you do not have reproducible builds, you are not protected even against yourself catching a backdoor. It is absolutely not acceptable to manage any amount of money in non-verifiable wallets. Yes, I'm just some dude. So what? Not being verifiable is still a gigantic no-no for wallet software.

**Comment by igorgue** [comment]
@Giszmo Pull requests are welcome. Fix it yourself since you're the one dude that care.

**Comment by Giszmo** [comment]
If I'm the only one who notices that you drive with your breaks broken, is it on my to fix them, too? I will make sure all your users will care cause it actually matters a lot and you being ignorant about it is very scary.

**Comment by igorgue** [comment]
@Giszmo You're not even a user, so what drive are we talking about?

Get out of here troll. Why don't you spend this time making your wallet better?

**Comment by Giszmo** [comment]
I want to make Bitcoin better and will probably work on WalletScrutiny long after I quit at Mycelium. I totally see the conflict of interest but so far, Mycelium pays me. WalletScrutiny doesn't.

**Comment by igorgue** [comment]
@Giszmo Hey same here, HODL is Free and Open Source, it's *not* what pay my bills, even then there are in reality way more pressing issues than what you complain about.

I recommend you to do the same, especially during these times of uncertainty may be working on Mycelium is more important than complaining about a very small wallet (nowhere near the users you have) not having reproducible builds, if you search online, we haven't really lost people's money.

And, again, I welcome you to stop wasting your time, and maybe make a little pull request fixing our build process, would be awesome!

**Comment by emanuelb** [comment]
The latest commit&version is reproducible, Containerfile I wrote to build the project in:
https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/193

**Comment by emanuelb** [comment]
Well, it's not reproducible to the app in google-play, the `libcore-lib.so` is reproducible when build with the exact same toolchain, so the question is: @igorgue on how+what environment was it build on (OS, other deps version which might affect the output? android-studio version? etc..)
more details in this comment and the ones after: https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/193#note_539669190
